name: speakmobilemvp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase (Auth & Analytics only)
  firebase_core: ^2.32.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  
  # UI Components
  fl_chart: ^0.69.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

  # Audio & Voice Processing
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_waveforms: ^1.0.4
  speech_to_text: ^7.0.0
  
  # Backend & Storage
  supabase_flutter: ^2.8.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.0

  # Networking & API
  dio: ^5.3.2
  json_annotation: ^4.8.1
  http: ^1.1.0

  # Web3 & Blockchain
  web3dart: ^2.7.1
  flutter_web3: ^2.1.9

  # Payment
  flutter_stripe: ^11.2.0
  pay: ^2.0.0
  razorpay_flutter: ^1.3.7

  # Utils
  logger: ^2.0.2+1
  flutter_dotenv: ^5.0.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  ffmpeg_kit_flutter: ^6.0.3
  record: ^5.0.4
  volume_controller: ^2.0.8
  device_info_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/contracts/
    - assets/payments/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/all the people.jpeg
  branding: assets/images/justagirlshoulders:head.jpeg
  color_dark: "#000000"
  image_dark: assets/images/all the people.jpeg
  branding_dark: assets/images/justagirlshoulders:head.jpeg

  android_12:
    image: assets/images/all the people.jpeg
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/all the people.jpeg
    icon_background_color_dark: "#000000"

  web: false
